# Generated by Django 3.2.10 on 2023-05-28 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_post_reads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reads',
            field=models.ManyToManyField(blank=True, related_name='reads_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
