# Generated by Django 3.2.10 on 2023-05-28 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='position',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='subjects',
            new_name='status',
        ),
    ]
